export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED'
export const INCREMENT = 'counter/INCREMENT'
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED'
export const DECREMENT = 'counter/DECREMENT'




// USER RELATED
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_LOGIN_IN_PROGRESS = 'USER_LOGIN_IN_PROGRESS'
export const USER_LOGIN_PROCESS_ENDED = 'USER_LOGIN_PROCESS_ENDED'
export const REQUEST_FOR_USER_SETTINGS_IN_PROGRESS = 'REQUEST_FOR_USER_SETTINGS_IN_PROGRESS'
export const RECEIVED_USER_SETTINGS = 'RECEIVED_USER_SETTINGS'
export const REQUEST_TO_CHANGE_TIME_ZONE_IN_PROGRESS = 'REQUEST_TO_CHANGE_TIME_ZONE_IN_PROGRESS'