export default {
    TOP_LEVEL_STATE_REDUCERS: {
        COUNTER_REDUCER: 'COUNTER_REDUCER',
        USER_REDUCER: 'USER_REDUCER',
    },

    STATE_INNER_OBJECT_NAMES: {
        COUNT: 'COUNT',
        IS_INCREMENTING: 'IS_INCREMENTING',
        IS_DECREMENTING: 'IS_DECREMENTING',

        // USER
        USER_EMAIL: 'USER_EMAIL',
        USER_SELECTED_TIMEZONE: 'USER_SELECTED_TIMEZONE',
        USER_LOGIN_IN_PROGRESS: 'USER_LOGIN_IN_PROGRESS',
        IS_RECEIVED_USER_SETTINGS: 'IS_RECEIVED_USER_SETTINGS',
    }
}