export default {
    TOP_LEVEL_STATE_REDUCERS: {
        COUNTER_REDUCER: 'COUNTER_REDUCER',
    },

    STATE_INNER_OBJECT_NAMES: {
        COUNT: 'COUNT',
        IS_INCREMENTING: 'IS_INCREMENTING',
        IS_DECREMENTING: 'IS_DECREMENTING',
    }
}